In [57]:
!nvidia-smi

Thu Jul 25 14:37:32 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.48       Driver Version: 517.48       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0    N/A /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [58]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu118


## Introduction to Tensors

## Creating tensors


In [59]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [60]:
type(scalar)

torch.Tensor

In [61]:
# number of dimentions
scalar.ndim

0

In [62]:
# get tensor back as python int
scalar.item()

7

In [63]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [64]:
vector.ndim

1

In [65]:
vector.shape

torch.Size([2])

In [66]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [67]:
MATRIX.ndim

2

In [68]:
MATRIX[0]

tensor([7, 8])

In [69]:
MATRIX.shape

torch.Size([2, 2])

In [70]:
# TENSOR
TENSOR = torch.tensor(([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]]))
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [71]:
TENSOR.ndim

3

In [72]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [73]:
# Create a random tensors of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3071, 0.4091, 0.8325, 0.2722],
        [0.6854, 0.4986, 0.7250, 0.8656],
        [0.0812, 0.1889, 0.2401, 0.4785]])

In [74]:
random_tensor.ndim

2

In [75]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [76]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [77]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [78]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [79]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [80]:
# use torch.arange()
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [82]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [83]:
# float 32 tensor (default one)
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
    device=None,  # what device is your tensor on
    requires_grad=False,  # whether or not to track gradients with this tensors operations
)
float_32_tensor

tensor([3., 6., 9.])

In [84]:
float_32_tensor.dtype

torch.float32

In [85]:
float_16_tensor = float_32_tensor.type(torch.float16) # or float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [86]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [87]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9120, 0.0506, 0.7006, 0.9968],
        [0.1602, 0.2874, 0.1489, 0.1408],
        [0.8251, 0.8133, 0.7183, 0.6870]])

In [88]:
some_tensor.size()

torch.Size([3, 4])

In [89]:
some_tensor.shape

torch.Size([3, 4])

In [90]:
# find out details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9120, 0.0506, 0.7006, 0.9968],
        [0.1602, 0.2874, 0.1489, 0.1408],
        [0.8251, 0.8133, 0.7183, 0.6870]])
Datatype of tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [91]:
# create a tensor
tensor = torch.tensor([1, 2, 3])

In [92]:
# add 10 to tensor
tensor + 10

tensor([11, 12, 13])

In [93]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [94]:
# substract 10
tensor - 10

tensor([-9, -8, -7])

In [95]:
# try out pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [96]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplcation (Dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dementions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [97]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))
# Error....

In [98]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6977, 0.8399],
        [0.7333, 1.3521]])

In [99]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.9104, 0.5417, 0.5702],
        [0.3077, 0.2506, 0.1091],
        [0.9744, 0.6003, 0.5849]])

In [100]:
# element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [101]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [102]:
tensor @ tensor

tensor(14)

In [103]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 4.99 ms


In [104]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

## One of the most common errors in deep learning: shape errors

In [105]:
# shapes for matrix multiplication
tensor_A = torch.tensor([
  [1, 2],
  [3, 4],
  [5, 6]
])

tensor_B = torch.tensor([
  [7, 10],
  [8, 11],
  [9, 12]
])

# torch.mm(tensor_A, tensor_B)
# torch.mm is the same as torch.matmu (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of ones of out tensors using a **transpose**.

A transpose switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
# the matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [112]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [108]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [109]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [111]:
# find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [113]:
torch.mean(x.type(torch.float32))

tensor(45.)