In [64]:
!nvidia-smi

Thu Jul 25 09:45:11 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.48       Driver Version: 517.48       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0    N/A /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [65]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu118


## Introduction to Tensors

## Creating tensors


In [66]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [67]:
type(scalar)

torch.Tensor

In [68]:
# number of dimentions
scalar.ndim

0

In [69]:
# get tensor back as python int
scalar.item()

7

In [70]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [71]:
vector.ndim

1

In [72]:
vector.shape

torch.Size([2])

In [73]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [74]:
MATRIX.ndim

2

In [75]:
MATRIX[0]

tensor([7, 8])

In [76]:
MATRIX.shape

torch.Size([2, 2])

In [77]:
# TENSOR
TENSOR = torch.tensor(([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]]))
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [78]:
TENSOR.ndim

3

In [79]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [80]:
# Create a random tensors of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3605, 0.7867, 0.2291, 0.3920],
        [0.4322, 0.3595, 0.8288, 0.7327],
        [0.6311, 0.6004, 0.3098, 0.6015]])

In [81]:
random_tensor.ndim

2

In [82]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [83]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [84]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [85]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [86]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [87]:
# use torch.arange()
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [89]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [90]:
# float 32 tensor (default one)
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
    device=None,  # what device is your tensor on
    requires_grad=False,  # whether or not to track gradients with this tensors operations
)
float_32_tensor

tensor([3., 6., 9.])

In [91]:
float_32_tensor.dtype

torch.float32

In [92]:
float_16_tensor = float_32_tensor.type(torch.float16) # or float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [93]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [94]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6715, 0.6028, 0.8335, 0.2865],
        [0.1326, 0.7897, 0.3367, 0.0343],
        [0.3025, 0.5839, 0.0701, 0.3645]])

In [95]:
some_tensor.size()

torch.Size([3, 4])

In [96]:
some_tensor.shape

torch.Size([3, 4])

In [97]:
# find out details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6715, 0.6028, 0.8335, 0.2865],
        [0.1326, 0.7897, 0.3367, 0.0343],
        [0.3025, 0.5839, 0.0701, 0.3645]])
Datatype of tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [98]:
# create a tensor
tensor = torch.tensor([1, 2, 3])

In [99]:
# add 10 to tensor
tensor + 10

tensor([11, 12, 13])

In [100]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [101]:
# substract 10
tensor - 10

tensor([-9, -8, -7])

In [102]:
# try out pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [103]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplcation (Dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dementions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

In [110]:
torch.rand(3, 2).shape

torch.Size([3, 2])

In [104]:
# element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [105]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [106]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2 ms


In [107]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 998 µs


tensor(14)

## One of the most common errors in deep learning: shape errors