In [1]:
!nvidia-smi

Sun Jul 21 10:48:06 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.48       Driver Version: 517.48       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0    N/A /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu118


## Introduction to Tensors

## Creating tensors


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
type(scalar)

torch.Tensor

In [5]:
# number of dimentions
scalar.ndim

0

In [6]:
# get tensor back as python int
scalar.item()

7

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# TENSOR
TENSOR = torch.tensor(([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]]))
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [24]:
# Create a random tensors of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2062, 0.4880, 0.2280, 0.8320],
        [0.1672, 0.4070, 0.3064, 0.9725],
        [0.3861, 0.8092, 0.7128, 0.5550]])

In [25]:
random_tensor.ndim

2

In [27]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)