In [83]:
!nvidia-smi

Sun Sep  8 10:57:09 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.48       Driver Version: 517.48       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0    N/A /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [84]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu118


## Introduction to Tensors

## Creating tensors


In [85]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [86]:
type(scalar)

torch.Tensor

In [87]:
# number of dimentions
scalar.ndim

0

In [88]:
# get tensor back as python int
scalar.item()

7

In [89]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [90]:
vector.ndim

1

In [91]:
vector.shape

torch.Size([2])

In [92]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [93]:
MATRIX.ndim

2

In [94]:
MATRIX[0]

tensor([7, 8])

In [95]:
MATRIX.shape

torch.Size([2, 2])

In [96]:
# TENSOR
TENSOR = torch.tensor(([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]]))
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [97]:
TENSOR.ndim

3

In [98]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [99]:
# Create a random tensors of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9104, 0.9305, 0.0672, 0.7800],
        [0.4197, 0.5125, 0.4805, 0.7552],
        [0.3462, 0.7040, 0.7735, 0.5268]])

In [100]:
random_tensor.ndim

2

In [101]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones


In [102]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [103]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [104]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [105]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [106]:
# use torch.arange()
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [108]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [109]:
# float 32 tensor (default one)
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
    device=None,  # what device is your tensor on
    requires_grad=False,  # whether or not to track gradients with this tensors operations
)
float_32_tensor

tensor([3., 6., 9.])

In [110]:
float_32_tensor.dtype

torch.float32

In [111]:
float_16_tensor = float_32_tensor.type(
    torch.float16
)  # or float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [112]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`


In [113]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3237, 0.8179, 0.0952, 0.3244],
        [0.8851, 0.4387, 0.9224, 0.4017],
        [0.1638, 0.3781, 0.0136, 0.5931]])

In [114]:
some_tensor.size()

torch.Size([3, 4])

In [115]:
some_tensor.shape

torch.Size([3, 4])

In [116]:
# find out details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3237, 0.8179, 0.0952, 0.3244],
        [0.8851, 0.4387, 0.9224, 0.4017],
        [0.1638, 0.3781, 0.0136, 0.5931]])
Datatype of tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication


In [117]:
# create a tensor
tensor = torch.tensor([1, 2, 3])

In [118]:
# add 10 to tensor
tensor + 10

tensor([11, 12, 13])

In [119]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [120]:
# substract 10
tensor - 10

tensor([-9, -8, -7])

In [121]:
# try out pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [122]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplcation (Dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dementions** must match:

- `(3, 2) @ (3, 2)` won't work
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

- `(2, 3) @ (3, 2)` -> `(2, 2)`
- `(3, 2) @ (2, 3)` -> `(3, 3)`


In [123]:
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))
# Error....

In [124]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[1.0365, 0.7857],
        [0.2975, 0.2026]])

In [125]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.6144, 0.5792, 0.3209],
        [0.6214, 0.5045, 0.3249],
        [0.7782, 0.4896, 0.4075]])

In [126]:
# element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [127]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [128]:
tensor @ tensor

tensor(14)

In [129]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2.99 ms


In [130]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

## One of the most common errors in deep learning: shape errors


In [131]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

# torch.mm(tensor_A, tensor_B)
# torch.mm is the same as torch.matmu (it's an alias for writing less code)
# torch.matmul(tensor_A, tensor_B)

In [132]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of ones of out tensors using a **transpose**.

A transpose switches the axes or dimensions of a given tensor.


In [133]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [134]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [135]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [136]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [137]:
# the matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(
    f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}"
)
print(
    f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match"
)
print("Output:\n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)


In [138]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [139]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [140]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [141]:
torch.mean(x.float())

tensor(45.)

In [142]:
# find the mean
# note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [143]:
#  find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Find the positional min and max


In [144]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [145]:
# find the position in tensor has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [146]:
x[0]

tensor(0)

In [147]:
# find the position in tensor that has the maximum vaue with argmax()
x.argmax()

tensor(9)

In [148]:
x[9]

tensor(90)

## Reshaping, Stacking, Squeezing and Unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - Combine multiple tenosrs on top of each other (vstack) or side by side (hstack)
- Squeeze - Removes all `1` dimentsion to a target tensor
- Unsequeeze - Add a `1` dimension to a target tensor
- Permute - Return a view of the input with dimenstions permuted (swapped) in a certain way


In [149]:
# let's create a tensor
x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [150]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [151]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [152]:
# add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [153]:
# let's create a tensor
x = torch.arange(1.0, 11.0)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [154]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [155]:
# let's create a tensor
x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [156]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [157]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [158]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [159]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [160]:
x_reshaped = torch.tensor([[5.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]])
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [161]:
# torch.squeeze()- remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [162]:
# torch.unsqueeze() - adds a single dimenstion to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# adds an extra dimension with unsqueeze
x_unsqeezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqeezed}")
print(f"New shape: {x_unsqeezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [163]:
# torch.unsqueeze() - adds a single dimenstion to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# adds an extra dimension with unsqueeze
x_unsqeezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqeezed}")
print(f"New shape: {x_unsqeezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [164]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))  # [height, width, colour_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [165]:
x_original[0, 0, 0] = 72821
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(72821.), tensor(72821.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.


In [167]:
# create a tensor
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [168]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [171]:
# let's index on the middle bracket (dim=1)
x[0, 0], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [175]:
# let's index on the most inner bracket (lat dimention)
x[0][0][0], x[0][1][1], x[0][2][2]

(tensor(1), tensor(5), tensor(9))

In [178]:
# you can aslo use ":" to select "all" of a target dimention
x[:, 0]

tensor([[1, 2, 3]])

In [183]:
# get all values of 0th and 1st dimentions but only index 1 of 2nd dimention
x[:, :, 1]

tensor([[2, 5, 8]])

In [185]:
# get all values of the 0 dimention but only the 1 index value of 1st and 2nd dimention
x[:, 1, 1]  # = x[0][1][1]

tensor([5])

In [186]:
# get index 0 of th 0th and 1st dimention and all values of 2nd dimention
x[0, 0, :]

tensor([1, 2, 3])

In [190]:
# index on x to return to 9
print(x[0][2][2])

# index on x to return to 3, 6, 9
print(x[:, :2])

tensor(9)
tensor([[[1, 2, 3],
         [4, 5, 6]]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
And becuase of this, PyTorch has functionality to interact with it.

- Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor -> NumPy -> `tensor.Tensor.numpy()`


In [191]:
import torch
import numpy as np

In [192]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(
    array
)  # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [193]:
array.dtype

dtype('float64')

In [194]:
tensor.dtype

torch.float64

In [195]:
# change the value of array what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [196]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [197]:
numpy_tensor.dtype

dtype('float32')

In [198]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

`start with random numbers -> tensor operation -> update random numbers to try and make them better representaions of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTOrch the concept of a **ranfom seed**.

Essentially what the random seed does is "flavour" the randomness.

In [219]:
import torch

# create two random tensor
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2383, 0.4195, 0.8830, 0.7097],
        [0.1388, 0.3716, 0.5892, 0.6352],
        [0.8044, 0.8362, 0.5234, 0.8989]])
tensor([[0.9362, 0.4627, 0.5380, 0.3519],
        [0.5922, 0.3002, 0.2096, 0.0082],
        [0.6838, 0.3730, 0.1890, 0.8070]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
